### ISSUE TITLE
Center Alignment

### ISSUE THREAD

**Issue by jrodl3r** [eldargab/easy-table#10]
How difficult do you think it would be to add center alignment on print + transposed output?
:beers:

**Comment by eldargab** [comment]
Do you mean something like this?

```
aaaaaa  bbbbbbb
  aa      bbb
 aaaa    bbbbb
```

**Comment by jrodl3r** [comment]
yes

**Comment by eldargab** [comment]
Note, that we can only position with precision up to one character.
There is no way to center align precisely when you have both even and odd lengths in the same column. 
If this is not a concern, the following will do the job:

```javascript
function center(str, width) {
  if (!width) return str
  var pad = (width - str.length) >>> 1
  return new Array(pad + 1).join(' ') + str
}

// use it like
t.cell('foo', 'bar baz', center)
```
