### ISSUE TITLE
Alignment problem for CJK characters

### ISSUE THREAD

**Issue by QiuZhiFei** [eldargab/easy-table#15]
<img width="429" alt="2017-04-05 9 25 19" src="https://cloud.githubusercontent.com/assets/3402799/24707524/7a1567e2-1a46-11e7-9c9c-580ffdfb5663.png">

**Comment by QiuZhiFei** [comment]
https://github.com/eldargab/easy-table/pull/16

**Comment by QiuZhiFei** [comment]
please release a new version ?  @eldargab

**Comment by eldargab** [comment]
New version released.
