### ISSUE TITLE
convert to TS, get more traction

### ISSUE THREAD

**Issue by ORESoftware** [eldargab/easy-table#23]
I am looking for a cli-table library written with TypeScript.

This lib might get more traction if it were written in TS?

**Comment by eldargab** [comment]
Hello,

Rewrite is not planned, but type definitions are already available - [@types/easy-table](https://www.npmjs.com/package/@types/easy-table). Hope, that will be enough.

**Comment by eldargab** [comment]
@nikeee hello, let's do it. PR is welcome.

**Comment by ORESoftware** [comment]
tbh this codebase is small, why not write it in TS? Separate type declarations are almost always out of sync.

**Comment by nikeee** [comment]
I think this would be the next step. Migration to TypeScript would not be that much.

> Separate type declarations are almost always out of sync.

Thats why they get removed from DT when the package is released.

**Comment by ORESoftware** [comment]
What I mean, is not only that the d.ts file(s) move to this repo, but that this whole repo is written in TS

**Comment by nikeee** [comment]
I know.
