### ISSUE TITLE
Support colorizing?

### ISSUE THREAD

**Issue by kenperkins** [eldargab/easy-table#8]
Have you considered any approaches to allow color for the table? either the column headers, footers, or cell values?

I tried a limited test, and it seemed to impact the row length using the `colors` packges for field values, so I figured I'd ask before doing any more research.

**Comment by eldargab** [comment]
As of `1.0` colors are supported

**Comment by WasabiFan** [comment]
Is there a way to intercept the drawing for a whole row so that I can colorize the background? If I pass colorized strings into the cell call, it only colorizes the text, and not the empty space for the whole row.

Past that, is there a way to add sub-headings for sections of the table?

**Comment by eldargab** [comment]
No, there is no such options
